In [1]:
import pandas as pd
df=pd.read_csv('messy_retail_orders.csv')
df

,OrderID,Customer Name,Email,City,Product Category,Product Name,Unit Price,Quantity,Discount,Payment Method,Order Status,Order Date
0,10680.0,Neha Das,neha.das106@gmail.com,Delhi,electronics,Power Bank,2677.37,2.0,15,cod,shipped,03-10-2024
1,10472.0,Vihaan Reddy,vihaan.reddy95@gmail.com,MUMBAI,Beauty,Perfume,492.17,3.0,0,COD,DELIVERED,16-05-2025
2,10643.0,Priya Chatterjee,priya.chatterjee37@gmail.com,delhi,Toys,Board Game,1550.63,3.0,0%,Debit Card,shipped,14/05/2025
3,10644.0,Anika Iyer,anika.iyer190@gmail.com,jaipur,Electronic,Bluetooth Speaker,2488.41,1.0,0%,Upi,Pending,05/02/2025
4,10747.0,Aadhya Gupta,aadhya.gupta97@gmail.com,HYDERABAD,toys,Building Blocks,NaN,2.0,0,DC,Returned,06/29/2025
...,...,...,...,...,...,...,...,...,...,...,...,...
813,10580.0,Sunita Pillai,sunita.pillai138@yahoo.com,Jaipur,electronics,LED Monitor,3998.58,2.0,20%,upi,Pending,07/07/2024
814,10503.0,Anika Das,anika.das222@gmail.com,Madras,Home&Kitchen,Mixer Grinder,216.45,2.0,10,DC,Canceled,18/12/2024
815,10538.0,Aadhya Mehta,aadhya.mehta238@yahoo.com,PUNE,clothing,Jacket,1351.31,1.0,5%,CC,Pending,27/03/2024
816,10197.0,REYANSH PILLAI,reyansh.pillai169@yahoo.com,Chennai,electronics,LED Monitor,946.04,2.0,0,COD,Returned,02/04/2024
817,10176.0,Reyansh Iyer,reyansh.iyer18@yahoo.com,bengaluru,Home & Kitchen,Non-stick Pan,₹1467.6,5.0,0,Upi,Returned,15-04-2025

In [2]:
#findinf the data type of the specific column
print(df["OrderID"].dtype)

float64

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 818 entries, 0 to 817
Data columns (total 12 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   OrderID           815 non-null    float64
 1   Customer Name     796 non-null    object
 2   Email             784 non-null    object
 3   City              792 non-null    object
 4   Product Category  815 non-null    object
 5   Product Name      815 non-null    object
 6   Unit Price        787 non-null    object
 7   Quantity          801 non-null    float64
 8   Discount          815 non-null    object
 9   Payment Method    804 non-null    object
 10  Order Status      815 non-null    object
 11  Order Date        797 non-null    object
dtypes: float64(2), object(10)
memory usage: 76.8+ KB

In [ ]:
#Changing the data of the particular column
df=df.dropna(subset=["OrderID"])
df["OrderID"]=df["OrderID"].astype(int)
df

,OrderID,Customer Name,Email,City,Product Category,Product Name,Unit Price,Quantity,Discount,Payment Method,Order Status,Order Date
0,10680,Neha Das,neha.das106@gmail.com,Delhi,electronics,Power Bank,2677.37,2.0,15,cod,shipped,03-10-2024
1,10472,Vihaan Reddy,vihaan.reddy95@gmail.com,MUMBAI,Beauty,Perfume,492.17,3.0,0,COD,DELIVERED,16-05-2025
2,10643,Priya Chatterjee,priya.chatterjee37@gmail.com,delhi,Toys,Board Game,1550.63,3.0,0%,Debit Card,shipped,14/05/2025
3,10644,Anika Iyer,anika.iyer190@gmail.com,jaipur,Electronic,Bluetooth Speaker,2488.41,1.0,0%,Upi,Pending,05/02/2025
4,10747,Aadhya Gupta,aadhya.gupta97@gmail.com,HYDERABAD,toys,Building Blocks,NaN,2.0,0,DC,Returned,06/29/2025
...,...,...,...,...,...,...,...,...,...,...,...,...
813,10580,Sunita Pillai,sunita.pillai138@yahoo.com,Jaipur,electronics,LED Monitor,3998.58,2.0,20%,upi,Pending,07/07/2024
814,10503,Anika Das,anika.das222@gmail.com,Madras,Home&Kitchen,Mixer Grinder,216.45,2.0,10,DC,Canceled,18/12/2024
815,10538,Aadhya Mehta,aadhya.mehta238@yahoo.com,PUNE,clothing,Jacket,1351.31,1.0,5%,CC,Pending,27/03/2024
816,10197,REYANSH PILLAI,reyansh.pillai169@yahoo.com,Chennai,electronics,LED Monitor,946.04,2.0,0,COD,Returned,02/04/2024
817,10176,Reyansh Iyer,reyansh.iyer18@yahoo.com,bengaluru,Home & Kitchen,Non-stick Pan,₹1467.6,5.0,0,Upi,Returned,15-04-2025

In [21]:
#finding the duplicates
print(df["Customer Name"].duplicated().sum())

0

In [26]:
#Removing the duplicates
df=df.drop_duplicates(subset=["Customer Name"])
df=df.drop_duplicates(subset=["Email"])

In [44]:
df["Product Name"] = df["Product Name"].astype("string")

C:\Users\Harsha vardhan\AppData\Local\Temp\ipykernel_26284\2522088230.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Product Name"] = df["Product Name"].astype("string")

In [6]:
#Converting the customer Name column into title to fix the upper and lower issue
df["Customer Name"]=df["Customer Name"].str.title()
df["City"]=df["City"].str.title()
df["Product Category"]=df["Product Category"].str.title()
df["Order Status"]=df["Order Status"].str.title()
df

,OrderID,Customer Name,Email,City,Product Category,Product Name,Unit Price,Quantity,Discount,Payment Method,Order Status,Order Date
0,10680.0,Neha Das,neha.das106@gmail.com,Delhi,Electronics,Power Bank,2677.37,2.0,15,Cash on Delivery,Shipped,03-10-2024
1,10472.0,Vihaan Reddy,vihaan.reddy95@gmail.com,Mumbai,Beauty,Perfume,492.17,3.0,0,Cash on Delivery,Delivered,16-05-2025
2,10643.0,Priya Chatterjee,priya.chatterjee37@gmail.com,Delhi,Toys,Board Game,1550.63,3.0,0%,Debit Card,Shipped,14/05/2025
3,10644.0,Anika Iyer,anika.iyer190@gmail.com,Jaipur,Electronic,Bluetooth Speaker,2488.41,1.0,0%,Upi,Pending,05/02/2025
4,10747.0,Aadhya Gupta,aadhya.gupta97@gmail.com,Hyderabad,Toys,Building Blocks,NaN,2.0,0,Debit Card,Returned,06/29/2025
...,...,...,...,...,...,...,...,...,...,...,...,...
813,10580.0,Sunita Pillai,sunita.pillai138@yahoo.com,Jaipur,Electronics,LED Monitor,3998.58,2.0,20%,upi,Pending,07/07/2024
814,10503.0,Anika Das,anika.das222@gmail.com,Madras,Home&Kitchen,Mixer Grinder,216.45,2.0,10,Debit Card,Canceled,18/12/2024
815,10538.0,Aadhya Mehta,aadhya.mehta238@yahoo.com,Pune,Clothing,Jacket,1351.31,1.0,5%,CREDIT CARD,Pending,27/03/2024
816,10197.0,Reyansh Pillai,reyansh.pillai169@yahoo.com,Chennai,Electronics,LED Monitor,946.04,2.0,0,Cash on Delivery,Returned,02/04/2024
817,10176.0,Reyansh Iyer,reyansh.iyer18@yahoo.com,Bengaluru,Home & Kitchen,Non-stick Pan,₹1467.6,5.0,0,Upi,Returned,15-04-2025

In [ ]:
#Replacing the Emails with the invalid emails that's ending with @yahoo.com
df["Email"]=df["Email"].str.replace("yahoo.com","gmail.com",regex=False)
df

,OrderID,Customer Name,Email,City,Product Category,Product Name,Unit Price,Quantity,Discount,Payment Method,Order Status,Order Date
0,10680,Neha Das,neha.das106@gmail.com,Delhi,electronics,Power Bank,2677.37,2.0,15,cod,shipped,03-10-2024
1,10472,Vihaan Reddy,vihaan.reddy95@gmail.com,MUMBAI,Beauty,Perfume,492.17,3.0,0,COD,DELIVERED,16-05-2025
2,10643,Priya Chatterjee,priya.chatterjee37@gmail.com,delhi,Toys,Board Game,1550.63,3.0,0%,Debit Card,shipped,14/05/2025
3,10644,Anika Iyer,anika.iyer190@gmail.com,jaipur,Electronic,Bluetooth Speaker,2488.41,1.0,0%,Upi,Pending,05/02/2025
4,10747,Aadhya Gupta,aadhya.gupta97@gmail.com,HYDERABAD,toys,Building Blocks,NaN,2.0,0,DC,Returned,06/29/2025
...,...,...,...,...,...,...,...,...,...,...,...,...
661,10576,Kavya Das,kavya.das71@gmail.com,Jaipur,electronics,Power Bank,2248.5,1.0,5,Upi,Shipped,13 Jul 2025
755,10662,Saanvi Joshi,saanvi.joshi27@gmail.com,New Delhi,Home&Kitchen,Non-stick Pan,2034.73,50.0,20,Upi,shipped,31/13/2024
777,10495,Reyansh Kapoor,reyansh.kapoor59@gmail.com,Ahmedabad,Beauty,Perfume,470.51,2.0,0,Upi,shipped,17 Jan 2024
779,10551,Saanvi Das,saanvi.das134 at gmail.com,Kolkata,Home&Kitchen,Mixer Grinder,1064.89,1.0,0,Cash on Delivery,cancelled,12/24/2024
784,10190,Neha Kumar,neha.kumar239@gmail.com,pune,toys,Puzzle Set,1905.02,3.0,0,NetBanking,Shipped,28-03-2025

In [36]:
df=df.dropna()

In [41]:
df["Product Category"]=df["Product Category"].str.replace("Electronics","Electronic")
df

C:\Users\Harsha vardhan\AppData\Local\Temp\ipykernel_26284\3285768199.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Product Category"]=df["Product Category"].str.replace("Electronics","Electronic")

,OrderID,Customer Name,Email,City,Product Category,Product Name,Unit Price,Quantity,Discount,Payment Method,Order Status,Order Date
0,10680,Neha Das,neha.das106@gmail.com,Delhi,Electronic,Power Bank,2677.37,2.0,15,cod,shipped,03-10-2024
1,10472,Vihaan Reddy,vihaan.reddy95@gmail.com,Mumbai,Beauty,Perfume,492.17,3.0,0,COD,DELIVERED,16-05-2025
2,10643,Priya Chatterjee,priya.chatterjee37@gmail.com,Delhi,Toys,Board Game,1550.63,3.0,0%,Debit Card,shipped,14/05/2025
3,10644,Anika Iyer,anika.iyer190@gmail.com,Jaipur,Electronic,Bluetooth Speaker,2488.41,1.0,0%,Upi,Pending,05/02/2025
5,10128,Myra Kapoor,myra.kapoor94@gmail.com,Kolkata,Grocery,Ghee 1L,409.35,99.0,15,COD,Returned,07/22/2025
...,...,...,...,...,...,...,...,...,...,...,...,...
661,10576,Kavya Das,kavya.das71@gmail.com,Jaipur,Electronic,Power Bank,2248.5,1.0,5,Upi,Shipped,13 Jul 2025
755,10662,Saanvi Joshi,saanvi.joshi27@gmail.com,New Delhi,Home&Kitchen,Non-stick Pan,2034.73,50.0,20,Upi,shipped,31/13/2024
777,10495,Reyansh Kapoor,reyansh.kapoor59@gmail.com,Ahmedabad,Beauty,Perfume,470.51,2.0,0,Upi,shipped,17 Jan 2024
779,10551,Saanvi Das,saanvi.das134 at gmail.com,Kolkata,Home&Kitchen,Mixer Grinder,1064.89,1.0,0,Cash on Delivery,cancelled,12/24/2024
784,10190,Neha Kumar,neha.kumar239@gmail.com,Pune,Toys,Puzzle Set,1905.02,3.0,0,NetBanking,Shipped,28-03-2025

In [46]:
print(df["Product Name"].dtype)
df

string

,OrderID,Customer Name,Email,City,Product Category,Product Name,Unit Price,Quantity,Discount,Payment Method,Order Status,Order Date
0,10680,Neha Das,neha.das106@gmail.com,Delhi,Electronic,Power Bank,2677.37,2.0,15,cod,shipped,03-10-2024
1,10472,Vihaan Reddy,vihaan.reddy95@gmail.com,Mumbai,Beauty,Perfume,492.17,3.0,0,COD,DELIVERED,16-05-2025
2,10643,Priya Chatterjee,priya.chatterjee37@gmail.com,Delhi,Toys,Board Game,1550.63,3.0,0%,Debit Card,shipped,14/05/2025
3,10644,Anika Iyer,anika.iyer190@gmail.com,Jaipur,Electronic,Bluetooth Speaker,2488.41,1.0,0%,Upi,Pending,05/02/2025
5,10128,Myra Kapoor,myra.kapoor94@gmail.com,Kolkata,Grocery,Ghee 1L,409.35,99.0,15,COD,Returned,07/22/2025
...,...,...,...,...,...,...,...,...,...,...,...,...
661,10576,Kavya Das,kavya.das71@gmail.com,Jaipur,Electronic,Power Bank,2248.5,1.0,5,Upi,Shipped,13 Jul 2025
755,10662,Saanvi Joshi,saanvi.joshi27@gmail.com,New Delhi,Home&Kitchen,Non-stick Pan,2034.73,50.0,20,Upi,shipped,31/13/2024
777,10495,Reyansh Kapoor,reyansh.kapoor59@gmail.com,Ahmedabad,Beauty,Perfume,470.51,2.0,0,Upi,shipped,17 Jan 2024
779,10551,Saanvi Das,saanvi.das134 at gmail.com,Kolkata,Home&Kitchen,Mixer Grinder,1064.89,1.0,0,Cash on Delivery,cancelled,12/24/2024
784,10190,Neha Kumar,neha.kumar239@gmail.com,Pune,Toys,Puzzle Set,1905.02,3.0,0,NetBanking,Shipped,28-03-2025

In [ ]:
#Removing the error in the unit price column
df["Unit Price"] = df["Unit Price"].str.replace("â‚¹", "", regex=False)
df.loc[26]

C:\Users\Harsha vardhan\AppData\Local\Temp\ipykernel_26284\2772763520.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Unit Price"] = df["Unit Price"].str.replace("â‚¹", "", regex=False)

OrderID                                      10205
Customer Name                    Vivaan Chatterjee
Email               vivaan.chatterjee218@gmail.com
City                                     Bengaluru
Product Category                    Home & Kitchen
Product Name                          Water Bottle
Unit Price                                 1074.01
Quantity                                       2.0
Discount                                        10
Payment Method                                 cod
Order Status                               shipped
Order Date                              13/03/2025
Name: 26, dtype: object

In [56]:
df["Quantity"].dtype

dtype('int64')

In [57]:
df["Quantity"]=df["Quantity"].astype(int)
df

C:\Users\Harsha vardhan\AppData\Local\Temp\ipykernel_26284\889426797.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Quantity"]=df["Quantity"].astype(int)

,OrderID,Customer Name,Email,City,Product Category,Product Name,Unit Price,Quantity,Discount,Payment Method,Order Status,Order Date
0,10680,Neha Das,neha.das106@gmail.com,Delhi,Electronic,Power Bank,2677.37,2,15,cod,shipped,03-10-2024
1,10472,Vihaan Reddy,vihaan.reddy95@gmail.com,Mumbai,Beauty,Perfume,492.17,3,0,COD,DELIVERED,16-05-2025
2,10643,Priya Chatterjee,priya.chatterjee37@gmail.com,Delhi,Toys,Board Game,1550.63,3,0%,Debit Card,shipped,14/05/2025
3,10644,Anika Iyer,anika.iyer190@gmail.com,Jaipur,Electronic,Bluetooth Speaker,2488.41,1,0%,Upi,Pending,05/02/2025
5,10128,Myra Kapoor,myra.kapoor94@gmail.com,Kolkata,Grocery,Ghee 1L,409.35,99,15,COD,Returned,07/22/2025
...,...,...,...,...,...,...,...,...,...,...,...,...
661,10576,Kavya Das,kavya.das71@gmail.com,Jaipur,Electronic,Power Bank,2248.5,1,5,Upi,Shipped,13 Jul 2025
755,10662,Saanvi Joshi,saanvi.joshi27@gmail.com,New Delhi,Home&Kitchen,Non-stick Pan,2034.73,50,20,Upi,shipped,31/13/2024
777,10495,Reyansh Kapoor,reyansh.kapoor59@gmail.com,Ahmedabad,Beauty,Perfume,470.51,2,0,Upi,shipped,17 Jan 2024
779,10551,Saanvi Das,saanvi.das134 at gmail.com,Kolkata,Home&Kitchen,Mixer Grinder,1064.89,1,0,Cash on Delivery,cancelled,12/24/2024
784,10190,Neha Kumar,neha.kumar239@gmail.com,Pune,Toys,Puzzle Set,1905.02,3,0,NetBanking,Shipped,28-03-2025

In [58]:
print(df["Quantity"].value_counts().sort_index())

Quantity
1      61
2      48
3      27
4      17
5      14
50      2
99      1
120     2
Name: count, dtype: int64

In [59]:
df[df["Quantity"] > 10]

,OrderID,Customer Name,Email,City,Product Category,Product Name,Unit Price,Quantity,Discount,Payment Method,Order Status,Order Date
5,10128,Myra Kapoor,myra.kapoor94@gmail.com,Kolkata,Grocery,Ghee 1L,409.35,99,15,COD,Returned,07/22/2025
87,10061,Kavya Rao,kavya.rao81@gmail.com,Bangalore,Clothing,Kurti,970.84,50,0,debit card,cancelled,16-05-2025
133,10398,Kavya Nair,kavya.nair50@gmail.com,Hyderbad,Toy,Building Blocks,652.15,120,10,upi,Canceled,08 Oct 2024
485,10573,Divya Gupta,divya.gupta157@gmail.com,Lucknow,Books,Biography,613.78,120,10,DC,Pending,12-06-2024
755,10662,Saanvi Joshi,saanvi.joshi27@gmail.com,New Delhi,Home&Kitchen,Non-stick Pan,2034.73,50,20,Upi,shipped,31/13/2024

In [61]:
df = df[~df["Quantity"].isin([50, 99, 120])]
df

,OrderID,Customer Name,Email,City,Product Category,Product Name,Unit Price,Quantity,Discount,Payment Method,Order Status,Order Date
0,10680,Neha Das,neha.das106@gmail.com,Delhi,Electronic,Power Bank,2677.37,2,15,cod,shipped,03-10-2024
1,10472,Vihaan Reddy,vihaan.reddy95@gmail.com,Mumbai,Beauty,Perfume,492.17,3,0,COD,DELIVERED,16-05-2025
2,10643,Priya Chatterjee,priya.chatterjee37@gmail.com,Delhi,Toys,Board Game,1550.63,3,0%,Debit Card,shipped,14/05/2025
3,10644,Anika Iyer,anika.iyer190@gmail.com,Jaipur,Electronic,Bluetooth Speaker,2488.41,1,0%,Upi,Pending,05/02/2025
6,10738,Suresh Rao,suresh.rao171@gmail.com,Mumbai,Home And Kitchen,Non-stick Pan,2896.5,5,15,NB,pending,24 Mar 2024
...,...,...,...,...,...,...,...,...,...,...,...,...
637,10692,Anika Iyer,anika.iyer232@gmail.com,Hyderabad,Sport,Yoga Mat,3543.93,2,0%,NB,DELIVERED,2024-01-05
661,10576,Kavya Das,kavya.das71@gmail.com,Jaipur,Electronic,Power Bank,2248.5,1,5,Upi,Shipped,13 Jul 2025
777,10495,Reyansh Kapoor,reyansh.kapoor59@gmail.com,Ahmedabad,Beauty,Perfume,470.51,2,0,Upi,shipped,17 Jan 2024
779,10551,Saanvi Das,saanvi.das134 at gmail.com,Kolkata,Home&Kitchen,Mixer Grinder,1064.89,1,0,Cash on Delivery,cancelled,12/24/2024
784,10190,Neha Kumar,neha.kumar239@gmail.com,Pune,Toys,Puzzle Set,1905.02,3,0,NetBanking,Shipped,28-03-2025

In [65]:
df["Discount"] = df["Discount"].str.replace("%", "", regex=False)
df

,OrderID,Customer Name,Email,City,Product Category,Product Name,Unit Price,Quantity,Discount,Payment Method,Order Status,Order Date
0,10680,Neha Das,neha.das106@gmail.com,Delhi,Electronic,Power Bank,2677.37,2,15,cod,shipped,03-10-2024
1,10472,Vihaan Reddy,vihaan.reddy95@gmail.com,Mumbai,Beauty,Perfume,492.17,3,0,COD,DELIVERED,16-05-2025
2,10643,Priya Chatterjee,priya.chatterjee37@gmail.com,Delhi,Toys,Board Game,1550.63,3,0,Debit Card,shipped,14/05/2025
3,10644,Anika Iyer,anika.iyer190@gmail.com,Jaipur,Electronic,Bluetooth Speaker,2488.41,1,0,Upi,Pending,05/02/2025
6,10738,Suresh Rao,suresh.rao171@gmail.com,Mumbai,Home And Kitchen,Non-stick Pan,2896.5,5,15,NB,pending,24 Mar 2024
...,...,...,...,...,...,...,...,...,...,...,...,...
637,10692,Anika Iyer,anika.iyer232@gmail.com,Hyderabad,Sport,Yoga Mat,3543.93,2,0,NB,DELIVERED,2024-01-05
661,10576,Kavya Das,kavya.das71@gmail.com,Jaipur,Electronic,Power Bank,2248.5,1,5,Upi,Shipped,13 Jul 2025
777,10495,Reyansh Kapoor,reyansh.kapoor59@gmail.com,Ahmedabad,Beauty,Perfume,470.51,2,0,Upi,shipped,17 Jan 2024
779,10551,Saanvi Das,saanvi.das134 at gmail.com,Kolkata,Home&Kitchen,Mixer Grinder,1064.89,1,0,Cash on Delivery,cancelled,12/24/2024
784,10190,Neha Kumar,neha.kumar239@gmail.com,Pune,Toys,Puzzle Set,1905.02,3,0,NetBanking,Shipped,28-03-2025

In [68]:
#Converting to the numeric
df["Discount"] = pd.to_numeric(df["Discount"])
df

,OrderID,Customer Name,Email,City,Product Category,Product Name,Unit Price,Quantity,Discount,Payment Method,Order Status,Order Date
0,10680,Neha Das,neha.das106@gmail.com,Delhi,Electronic,Power Bank,2677.37,2,15,cod,shipped,03-10-2024
1,10472,Vihaan Reddy,vihaan.reddy95@gmail.com,Mumbai,Beauty,Perfume,492.17,3,0,COD,DELIVERED,16-05-2025
2,10643,Priya Chatterjee,priya.chatterjee37@gmail.com,Delhi,Toys,Board Game,1550.63,3,0,Debit Card,shipped,14/05/2025
3,10644,Anika Iyer,anika.iyer190@gmail.com,Jaipur,Electronic,Bluetooth Speaker,2488.41,1,0,Upi,Pending,05/02/2025
6,10738,Suresh Rao,suresh.rao171@gmail.com,Mumbai,Home And Kitchen,Non-stick Pan,2896.5,5,15,NB,pending,24 Mar 2024
...,...,...,...,...,...,...,...,...,...,...,...,...
637,10692,Anika Iyer,anika.iyer232@gmail.com,Hyderabad,Sport,Yoga Mat,3543.93,2,0,NB,DELIVERED,2024-01-05
661,10576,Kavya Das,kavya.das71@gmail.com,Jaipur,Electronic,Power Bank,2248.5,1,5,Upi,Shipped,13 Jul 2025
777,10495,Reyansh Kapoor,reyansh.kapoor59@gmail.com,Ahmedabad,Beauty,Perfume,470.51,2,0,Upi,shipped,17 Jan 2024
779,10551,Saanvi Das,saanvi.das134 at gmail.com,Kolkata,Home&Kitchen,Mixer Grinder,1064.89,1,0,Cash on Delivery,cancelled,12/24/2024
784,10190,Neha Kumar,neha.kumar239@gmail.com,Pune,Toys,Puzzle Set,1905.02,3,0,NetBanking,Shipped,28-03-2025

In [70]:
print(df["Discount"].dtype)

int64

In [ ]:
#adding a new column
df["Discount_Display"] = df["Discount"].astype(str) + "%"
df

,OrderID,Customer Name,Email,City,Product Category,Product Name,Unit Price,Quantity,Discount,Payment Method,Order Status,Order Date,Discount_Display
0,10680,Neha Das,neha.das106@gmail.com,Delhi,Electronic,Power Bank,2677.37,2,15,cod,shipped,03-10-2024,15%
1,10472,Vihaan Reddy,vihaan.reddy95@gmail.com,Mumbai,Beauty,Perfume,492.17,3,0,COD,DELIVERED,16-05-2025,0%
2,10643,Priya Chatterjee,priya.chatterjee37@gmail.com,Delhi,Toys,Board Game,1550.63,3,0,Debit Card,shipped,14/05/2025,0%
3,10644,Anika Iyer,anika.iyer190@gmail.com,Jaipur,Electronic,Bluetooth Speaker,2488.41,1,0,Upi,Pending,05/02/2025,0%
6,10738,Suresh Rao,suresh.rao171@gmail.com,Mumbai,Home And Kitchen,Non-stick Pan,2896.5,5,15,NB,pending,24 Mar 2024,15%
...,...,...,...,...,...,...,...,...,...,...,...,...,...
637,10692,Anika Iyer,anika.iyer232@gmail.com,Hyderabad,Sport,Yoga Mat,3543.93,2,0,NB,DELIVERED,2024-01-05,0%
661,10576,Kavya Das,kavya.das71@gmail.com,Jaipur,Electronic,Power Bank,2248.5,1,5,Upi,Shipped,13 Jul 2025,5%
777,10495,Reyansh Kapoor,reyansh.kapoor59@gmail.com,Ahmedabad,Beauty,Perfume,470.51,2,0,Upi,shipped,17 Jan 2024,0%
779,10551,Saanvi Das,saanvi.das134 at gmail.com,Kolkata,Home&Kitchen,Mixer Grinder,1064.89,1,0,Cash on Delivery,cancelled,12/24/2024,0%
784,10190,Neha Kumar,neha.kumar239@gmail.com,Pune,Toys,Puzzle Set,1905.02,3,0,NetBanking,Shipped,28-03-2025,0%

In [ ]:
#Droping the unwanted columns
df = df.drop(columns=["Discount"])
df

,OrderID,Customer Name,Email,City,Product Category,Product Name,Unit Price,Quantity,Payment Method,Order Status,Order Date,Discount_Display
0,10680,Neha Das,neha.das106@gmail.com,Delhi,Electronic,Power Bank,2677.37,2,cod,shipped,03-10-2024,15%
1,10472,Vihaan Reddy,vihaan.reddy95@gmail.com,Mumbai,Beauty,Perfume,492.17,3,COD,DELIVERED,16-05-2025,0%
2,10643,Priya Chatterjee,priya.chatterjee37@gmail.com,Delhi,Toys,Board Game,1550.63,3,Debit Card,shipped,14/05/2025,0%
3,10644,Anika Iyer,anika.iyer190@gmail.com,Jaipur,Electronic,Bluetooth Speaker,2488.41,1,Upi,Pending,05/02/2025,0%
6,10738,Suresh Rao,suresh.rao171@gmail.com,Mumbai,Home And Kitchen,Non-stick Pan,2896.5,5,NB,pending,24 Mar 2024,15%
...,...,...,...,...,...,...,...,...,...,...,...,...
637,10692,Anika Iyer,anika.iyer232@gmail.com,Hyderabad,Sport,Yoga Mat,3543.93,2,NB,DELIVERED,2024-01-05,0%
661,10576,Kavya Das,kavya.das71@gmail.com,Jaipur,Electronic,Power Bank,2248.5,1,Upi,Shipped,13 Jul 2025,5%
777,10495,Reyansh Kapoor,reyansh.kapoor59@gmail.com,Ahmedabad,Beauty,Perfume,470.51,2,Upi,shipped,17 Jan 2024,0%
779,10551,Saanvi Das,saanvi.das134 at gmail.com,Kolkata,Home&Kitchen,Mixer Grinder,1064.89,1,Cash on Delivery,cancelled,12/24/2024,0%
784,10190,Neha Kumar,neha.kumar239@gmail.com,Pune,Toys,Puzzle Set,1905.02,3,NetBanking,Shipped,28-03-2025,0%

In [5]:
df["Payment Method"] = df["Payment Method"].str.replace("COD", "Cash on Delivery", regex=False)
df["Payment Method"] = df["Payment Method"].str.replace("cod", "Cash on Delivery", regex=False)
df["Payment Method"] = df["Payment Method"].str.replace("DC", "Debit Card", regex=False)
df["Payment Method"] = df["Payment Method"].str.replace("debit card", "Debit Card", regex=False)
df["Payment Method"] = df["Payment Method"].str.replace("credit card", "CREDIT CARD", regex=False)
df["Payment Method"] = df["Payment Method"].str.replace("NB", "Net Banking", regex=False)
df["Payment Method"] = df["Payment Method"].str.replace("CC", "CREDIT CARD", regex=False)
df

,OrderID,Customer Name,Email,City,Product Category,Product Name,Unit Price,Quantity,Discount,Payment Method,Order Status,Order Date
0,10680.0,Neha Das,neha.das106@gmail.com,Delhi,electronics,Power Bank,2677.37,2.0,15,Cash on Delivery,shipped,03-10-2024
1,10472.0,Vihaan Reddy,vihaan.reddy95@gmail.com,MUMBAI,Beauty,Perfume,492.17,3.0,0,Cash on Delivery,DELIVERED,16-05-2025
2,10643.0,Priya Chatterjee,priya.chatterjee37@gmail.com,delhi,Toys,Board Game,1550.63,3.0,0%,Debit Card,shipped,14/05/2025
3,10644.0,Anika Iyer,anika.iyer190@gmail.com,jaipur,Electronic,Bluetooth Speaker,2488.41,1.0,0%,Upi,Pending,05/02/2025
4,10747.0,Aadhya Gupta,aadhya.gupta97@gmail.com,HYDERABAD,toys,Building Blocks,NaN,2.0,0,Debit Card,Returned,06/29/2025
...,...,...,...,...,...,...,...,...,...,...,...,...
813,10580.0,Sunita Pillai,sunita.pillai138@yahoo.com,Jaipur,electronics,LED Monitor,3998.58,2.0,20%,upi,Pending,07/07/2024
814,10503.0,Anika Das,anika.das222@gmail.com,Madras,Home&Kitchen,Mixer Grinder,216.45,2.0,10,Debit Card,Canceled,18/12/2024
815,10538.0,Aadhya Mehta,aadhya.mehta238@yahoo.com,PUNE,clothing,Jacket,1351.31,1.0,5%,CREDIT CARD,Pending,27/03/2024
816,10197.0,REYANSH PILLAI,reyansh.pillai169@yahoo.com,Chennai,electronics,LED Monitor,946.04,2.0,0,Cash on Delivery,Returned,02/04/2024
817,10176.0,Reyansh Iyer,reyansh.iyer18@yahoo.com,bengaluru,Home & Kitchen,Non-stick Pan,₹1467.6,5.0,0,Upi,Returned,15-04-2025

In [13]:
#changing the date format
df["Order Date"] = pd.to_datetime(
    df["Order Date"],
    errors="coerce"
)

In [15]:
print(df["Order Date"].dtype)

datetime64[ns]

In [18]:
df["Order Date"] = pd.to_datetime(
    df["Order Date"],
    format="%d-%m-%Y",
    errors="coerce"
)
df

,OrderID,Customer Name,Email,City,Product Category,Product Name,Unit Price,Quantity,Discount,Payment Method,Order Status,Order Date
0,10680.0,Neha Das,neha.das106@gmail.com,Delhi,Electronics,Power Bank,2677.37,2.0,15,Cash on Delivery,Shipped,2024-03-10
1,10472.0,Vihaan Reddy,vihaan.reddy95@gmail.com,Mumbai,Beauty,Perfume,492.17,3.0,0,Cash on Delivery,Delivered,NaT
2,10643.0,Priya Chatterjee,priya.chatterjee37@gmail.com,Delhi,Toys,Board Game,1550.63,3.0,0%,Debit Card,Shipped,NaT
3,10644.0,Anika Iyer,anika.iyer190@gmail.com,Jaipur,Electronic,Bluetooth Speaker,2488.41,1.0,0%,Upi,Pending,NaT
4,10747.0,Aadhya Gupta,aadhya.gupta97@gmail.com,Hyderabad,Toys,Building Blocks,NaN,2.0,0,Debit Card,Returned,NaT
...,...,...,...,...,...,...,...,...,...,...,...,...
813,10580.0,Sunita Pillai,sunita.pillai138@yahoo.com,Jaipur,Electronics,LED Monitor,3998.58,2.0,20%,upi,Pending,NaT
814,10503.0,Anika Das,anika.das222@gmail.com,Madras,Home&Kitchen,Mixer Grinder,216.45,2.0,10,Debit Card,Canceled,NaT
815,10538.0,Aadhya Mehta,aadhya.mehta238@yahoo.com,Pune,Clothing,Jacket,1351.31,1.0,5%,CREDIT CARD,Pending,NaT
816,10197.0,Reyansh Pillai,reyansh.pillai169@yahoo.com,Chennai,Electronics,LED Monitor,946.04,2.0,0,Cash on Delivery,Returned,NaT
817,10176.0,Reyansh Iyer,reyansh.iyer18@yahoo.com,Bengaluru,Home & Kitchen,Non-stick Pan,₹1467.6,5.0,0,Upi,Returned,NaT

In [26]:
print(df.columns)

Index(['OrderID', 'Customer Name', 'Email', 'City', 'Product Category',
       'Product Name', 'Unit Price', 'Quantity', 'Discount', 'Payment Method',
       'Order Status'],
      dtype='object')

In [ ]:
#Removing unwanted spaces from all column names
df.columns = df.columns.str.strip()